---
# See https://github.com/ansible/devtools/blob/main/.github/workflows/ack.yml
name: ack
"on":
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
  issues:
    types: [opened, reopened]

jobs:
  ack:
    uses: ssbarnea/devtools/.github/workflows/ack.yml@main
