name: check

on:
  # create:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1.2.0

      - name: Check out src from Git
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0  # needed by setuptools-scm

      - name: Display git info about clone
        run: git tag --points-at HEAD

      # - name: Now we fail
      #  run: exit 0
