name: check

on:
  # create:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ssbarnea/ansible-lint@v6.16.3
