name: release

on:
  # workflow_run:
  #   workflows: [check]
  #   # branches:
  #   #   - main
  #   #   - 'releases/**'
  #   types:
  #     - completed  # remember completed does not mean success!
  #   create:
  create:
    tags:

jobs:
  check:
    runs-on: ubuntu-latest
    uses: ssbarnea/gha-playground/.github/workflows/check.yml@main

  release:
    environment: release
    name: release
    needs: check

    runs-on: ubuntu-latest
    steps:
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1.2.0

      - name: Check out src from Git
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0  # needed by setuptools-scm

      - name: Display git info about clone
        run: git tag --points-at HEAD

      - name: Fail if checks did not pass previously
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: exit 1
