name: release

on:
  workflow_run:
    workflows: [dump]
    # branches:
    #   - main
    #   - 'releases/**'
    types:
      - completed  # remember completed does not mean success!
    create:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed by setuptools-scm

      - name: Display git info about clone
        run: git tag --points-at HEAD
